Homework 1: Introduction to Machine Learning

Deadline:
28 September 2026 (Mon), 19:00

Questions
Answer the questions below to complete your homework.

1. Pandas version (1 point)

In [91]:
import pandas as pd
import numpy as np

In [92]:
print(pd.__version__)

3.0.6


2. Records count (1 point)


[ ] 5000

[ ] 9000

[x] 10000

[ ] 15000

In [93]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
print(df.shape[0])

10000


3. Fuel types (1 point)


[ ] 1

[ ] 2

[x] 3

[ ] 4

In [94]:
df['fuel_type'].nunique()

3

4. Missing values (1 point)


[] 0

[ ] 1

[x] 2

[ ] 3

[ ] 4

In [95]:
miss_col = df.isnull().sum()
int(miss_col[miss_col > 0].count())

2

5. Max fuel efficiency (1 point)


[ ] 21.2

[ ] 31.2

[x] 41.2

[ ] 51.2

In [125]:
float(df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max())

41.2

6. Median value of horsepower (1 point)


[ ] Yes, it increased

[x] Yes, it decreased

[ ] No

In [97]:
med_1 = int(df['horsepower'].median())

1. Find the median value of the `horsepower` column in the dataset.

2. Next, calculate the most frequent value of the same `horsepower` column.

In [98]:
fil_mis = df['horsepower'].mode()[0]

In [99]:
med_2 = int(df['horsepower'].fillna(fil_mis).median())

In [100]:
med_2

252

## Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`.
   To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply
   the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

- 0.0369
- 0.369
- 3.69
- 36.9

In [114]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
asia = df[df["origin"] == "Asia"]
asia

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1


In [102]:
import numpy as np

In [119]:
first7 = asia[['vehicle_weight','model_year']].head(7)
first7
X = np.array(first7)
X.T
XTX = X.T @ X

In [121]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [122]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv


array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [106]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [123]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv @ X.T @ y
float(w.sum())

0.36919696904925486

In [124]:
w.shape
w

array([0.13644777, 0.2327492 ])